### ISSUE TITLE
Problem runing the project

### ISSUE THREAD

**Issue by walldir** [AnirudhaS/OMR-Scanner#1]
Sorry but i'm having a problem while runing you project, some folder are missing :
string path = @"D:\OMRSoft\FileInfo";
public static string connection_string = @"data source=D:\OMRSoft\Database\OMRSoft.s3db; Version=3;";

Can you help me?
Thanks, i'll be waiting for you reply.

**Comment by AnirudhaS** [comment]
@walldir I have made changes to the Readme file. Refer to it.
